var = input('Digite algo: ')
print('Tipo:',type(var))
print('É alfanumérico?',var.isalnum())
print('É numérico?',var.isnumeric())
print('É alfabético?',var.isalpha())
print('É ASCII?',var.isascii())
print('É minúsculo?',var.islower())
print('É maiúsculo?',var.isupper())
print('É decimal?',var.isdecimal())
print('É digito?',var.isdigit())
print('É título?',var.istitle())
print('É espaço?', var.isspace())
print('É imprimível?', var.isprintable())
print('É identificador?', var.isidentifier())
