nome =  input('Qual é o seu nome completo: ').strip()
print('Analizando o seu nome...')
print('Seu nome em maiúsculas: ' + nome.upper())
print('Seu nome em minúsculas: ' + nome.lower())
print('Seu nome completo tem {} letras'.format(len(nome.replace(' ',''))))
#print('E o primeiro nome tem {} letras'.format(nome.find(' ')))
print('E o primeiro nome tem {} letras'.format(len(nome.split()[0])))
